config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'
  get '/search', to: 'posts#search', as: 'search'
  resources :posts
  resources :authors, path: 'author', only: %i[show]
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/post.rb
class Post < ApplicationRecord
  # FriendlyId
  extend FriendlyId
  friendly_id :title, use: :slugged

  # Search
  include PgSearch::Model
  pg_search_scope :search_by_title_and_content, against: %i[title content], using: { tsearch: { prefix: true } }

  # Associations
  belongs_to :user

  # Active Storage
  has_one_attached :thumbnail

  # Scopes
  default_scope { order(created_at: :DESC) }
  scope :authored_by, ->(name) { where(user: name) }

  # Validations
  validates :title, presence: true, length: { minimum: 10 }
  validates :content, presence: true, length: { minimum: 100 }
  validate :thumbnail_validation
  validate :thumbnail_mime_type

  def date
    created_at.strftime('%B %d, %Y')
  end

  def next
    Post.unscope(:order).where('id > ?', id).order(id: :ASC).first
  end

  def previous
    Post.unscope(:order).where('id < ?', id).order(id: :DESC).first
  end

  private

  def should_generate_new_friendly_id?
    title_changed?
  end

  def thumbnail_validation
    errors.add(:thumbnail, 'must have a file') unless thumbnail.attached?
  end

  def thumbnail_mime_type
    return unless thumbnail.attached? && !thumbnail.content_type.in?(%w[image/jpeg image/png])

    errors.add(:thumbnail, 'must be an image')
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Callbacks
  before_save :set_full_name

  # FriendlyId
  extend FriendlyId
  friendly_id :full_name, use: :slugged

  # Devise
  ## Include default devise modules. Others available are:
  ## :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable, :recoverable, :rememberable, :validatable

  # Associations
  has_many :posts, dependent: :destroy

  # Enum
  enum role: %i[subscriber editor]

  # Validations
  validates :first_name, presence: true
  validates :last_name, presence: true

  private

  def set_full_name
    self.full_name = [first_name, last_name].join(' ')
  end

  def should_generate_new_friendly_id?
    first_name_changed? || last_name_changed?
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include Pundit
  include Pagy::Backend

  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?

  # Pundit: white-list approach.
  after_action :verify_authorized, except: :index, unless: :skip_pundit?
  after_action :verify_policy_scoped, only: :index, unless: :skip_pundit?

  private

  def skip_pundit?
    devise_controller? || params[:controller] =~ /(^pages$)/
  end

  protected

  def after_sign_up_path_for(_resource)
    root_path
  end

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: %i[first_name last_name])
    devise_parameter_sanitizer.permit(:account_update, keys: %i[first_name last_name])
  end
end

app/controllers/authors_controller.rb
class AuthorsController < ApplicationController
  skip_before_action :authenticate_user!, only: %i[show]

  def show
    @author = User.friendly.find(params[:id])
    authorize @author
    @pagy, @posts = pagy(Post.authored_by(@author), items: 6)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: %i[home]

  def home
    @posts = Post.take(5)
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: %i[show edit update destroy]
  skip_before_action :authenticate_user!, only: %i[show search]

  def show; end

  def new
    @post = Post.new
    authorize @post
  end

  def create
    @post = Post.new(post_strong_params)
    authorize @post
    @post.user = current_user
    if @post.save
      redirect_to post_path(@post)
    else
      render :new
    end
  end

  def edit; end

  def update
    @post.update(post_strong_params)
    if @post.save
      redirect_to post_path(@post)
    else
      render :edit
    end
  end

  def destroy
    @post.destroy
    redirect_to root_path
  end

  def search
    @query = params[:query][:title]
    @posts = Post.search_by_title_and_content(@query)
    authorize @posts
  end

  private

  def set_post
    @post = Post.friendly.find(params[:id])
    authorize @post
  end

  def post_strong_params
    params.require(:post).permit(:title, :content, :thumbnail)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  include Pagy::Frontend

  def page_title(separator = ' // ')
    [content_for(:title), DEFAULT_META["meta_title"]].compact.join(separator).html_safe
  end

  def custom_page_title(title)
    content_for(:title) { title }
  end

  def current_controller?(name)
    name.include?(controller.controller_name)
  end
end

app/helpers/meta_tags_helper.rb
module MetaTagsHelper
  def meta_description
    content_for?(:meta_description) ? content_for(:meta_description) : DEFAULT_META["meta_description"]
  end

  def meta_image
    meta_image = (content_for?(:meta_image) ? content_for(:meta_image) : DEFAULT_META["meta_image"])
    # little twist to make it work equally with an asset or a url
    meta_image.starts_with?("http") ? meta_image : image_url(meta_image)
  end
end

app/helpers/post_helper.rb
module PostHelper
  def markdown(article)
    options = {
      filter_html: true,
      link_attributes: { rel: 'nofollow' }
    }
    extensions = {
      autolink: true
    }
    renderer = Redcarpet::Render::HTML.new(options)
    markdown = Redcarpet::Markdown.new(renderer, extensions)
    markdown.render(article).html_safe
  end

  def excerpt(article)
    markdown = Redcarpet::Markdown.new(Redcarpet::Render::StripDown)
    truncate(markdown.render(article).html_safe, length: 250, separator: ' ')
  end
end

app/views/authors/show.html.erb
<% custom_page_title(@author.full_name) %>
<div class="container-lg py-4">
  <div class="d-flex align-items-end justify-content-between">
    <h1 class="m-0"><%= @author.full_name %></h1>
    <span>
    <% if current_user == @author %>
      <%= link_to edit_user_registration_path do %>
        <i class="fas fa-pencil-alt ms-2 mb-2 fs-5"></i>
      <% end %>
    <% end %>
    <%= mail_to @author.email do %>
      <i class="fas fa-at ms-2 mb-2 fs-5"></i>
    <% end %>
    </span>
  </div>
  <hr>
  <p class="mb-4"><%= @author.biography %></p>
  <h2>More from <%= @author.full_name %></h2>
  <hr>
  <turbo-frame>
    <div class="row">
      <% @posts.each do |post| %>
        <%= render 'posts/partials/horizontal_card', post: post %>
      <% end %>
    </div>
    <%= render partial: 'shared/pagy', locals: { pagy: @pagy } %>
  </turbo-frame>
</div>

app/views/layouts/_social_meta_tags.html.erb
<meta name="description" content="<%= meta_description %>">
<!-- Facebook Open Graph data -->
<meta property="og:title" content="<%= page_title %>">
<meta property="og:type" content="website">
<meta property="og:url" content="<%= request.original_url %>">
<meta property="og:image" content="<%= meta_image %>">
<meta property="og:description" content="<%= meta_description %>">
<meta property="og:site_name" content="<%= DEFAULT_META["meta_title"] %>">
<!-- Twitter Card data -->
<meta name="twitter:card" content="summary_large_image">
<meta name="twitter:title" content="<%= page_title %>">
<meta name="twitter:description" content="<%= meta_description %>">
<meta name="twitter:image:src" content="<%= meta_image %>">

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= page_title %></title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= render 'layouts/social_meta_tags' %>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <!-- 'data-turbolinks-track': 'reload' -->
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload', defer: true %>
    <%= favicon_link_tag asset_path('favicon.svg') %>
  </head>
  <body>
    <%= render 'shared/navbar' %>
    <%= render 'shared/flashes' %>
    <div class="body-content">
      <%= yield %>
    </div>
    <%= render 'shared/footer' %>
  </body>
</html>

app/views/pages/home.html.erb
<div class="container-lg">
  <h1 class="d-none">All posts</h1>
  <% @posts.each do |post| %>
    <% if post == @posts.first %>
      <%= render 'posts/partials/main_card', post: post %>
    <% else %>
      <%= render 'posts/partials/horizontal_card', post: post %>
    <% end %>
  <% end %>
</div>

app/views/posts/_post_form.html.erb
<%= javascript_pack_tag 'post' %>
<%= simple_form_for(@post) do |f| %>
  <div class="row">
    <div class="col-12 col-md-8">
      <%= f.input :title %>
      <%= f.input :content, input_html: { rows: 10, id: "post-editor" } %>
    </div>
    <div class="col-12 col-md-4">
      <%= f.input :thumbnail %>
      <%= f.button :submit, class: "btn-primary" %>
    </div>
  </div>
<% end %>

app/views/posts/edit.html.erb
<% custom_page_title("Edit post") %>
<div class="container-lg py-4">
  <h2>Edit post</h2>
  <%= render 'posts/partials/form' %>
</div>

app/views/posts/new.html.erb
<% custom_page_title("New post") %>
<div class="container-lg py-4">
  <h2>New post</h2>
  <%= render 'posts/partials/form' %>
</div>

app/views/posts/partials/_form.html.erb
<%= simple_form_for(@post) do |f| %>
  <div class="row">
    <div class="col-12 col-md-8">
      <%= f.input :title %>
      <%= f.input :content, input_html: { rows: 10 } %>
    </div>
    <div class="col-12 col-md-4">
      <%= f.input :thumbnail, required: true, input_html: { accept: "image/jpeg, image/png" } %>
      <% if @post.thumbnail.attached? %>
        <%= cl_image_tag @post.thumbnail.key, width: 1000, crop: :fill, id: "post_thumbnail_preview", class: "form-control p-2 mb-3" %>
      <% else %>
        <%= image_tag "", id: "post_thumbnail_preview", class: "d-none form-control p-2 mb-3" %>
      <% end %>
      <%= f.button :submit, class: "btn-primary w-100" %>
    </div>
  </div>
<% end %>
<%= javascript_pack_tag 'post' %>

app/views/posts/partials/_horizontal_card.html.erb
<div class="col-12">
  <div class="row card-post mb-4">
    <div class="col-4 col-md-3 pe-0 card-post-thumbnail">
      <%= link_to post_path(post) do %>
        <picture>
          <source srcset="<%= cl_image_path post.thumbnail.key, width: 230, height: 230, crop: :fill, quality: 100 %> 1x, <%= cl_image_path post.thumbnail.key, width: 460, height: 460, crop: :fill, quality: 100 %> 2x" media="(max-width: 767.98px)">
          <source srcset="<%= cl_image_path post.thumbnail.key, width: 264, height: 176, crop: :fill, quality: 100 %> 1x, <%= cl_image_path post.thumbnail.key, width: 528, height: 352, crop: :fill, quality: 100 %> 2x" media="(min-width: 768px)">
          <%= cl_image_tag post.thumbnail.key, width: 264, height: 176, crop: :fill, quality: 100, alt: post.title %>
        </picture>
      <% end %>
    </div>
    <div class="col-8 col-md-9 card-post-content">
      <h3 class="card-post-title mb-3"><%= link_to post.title, post_path(post) %></h3>
      <div class="card-post-info">
        <% unless current_page?(root_path) %>
          <p class="fs-6"><%= excerpt(post.content) %></p>
        <% end %>
        <% unless current_controller?('authors') %>
          <span class="text-uppercase fw-bold">by <%= post.user.full_name %></span>
          <div class="d-inline post-separator"></div>
        <% end %>
        <time class="text-uppercase fw-light"><%= post.date %></time>
      </div>
    </div>
  </div>
</div>

app/views/posts/partials/_main_card.html.erb
<div class="card-main-post mb-4">
  <div class="card-main-post-thumbnail">
    <%= link_to post_path(post) do %>
      <picture>
          <source srcset="<%= cl_image_path post.thumbnail.key, width: 768, height: 768, crop: :fill, quality: 100 %> 1x, <%= cl_image_path post.thumbnail.key, width: 1536, height: 1536, crop: :fill, quality: 100 %> 2x" media="(max-width: 767.98px)">
          <source srcset="<%= cl_image_path post.thumbnail.key, width: 1140, height: 600, crop: :fill, quality: 100 %>" media="(min-width: 768px)">
          <%= cl_image_tag post.thumbnail.key, width: 1140, height: 600, crop: :fill, quality: 100, alt: post.title %>
        </picture>
    <% end %>
  </div>
  <div class="card-main-post-content p-4 pt-0">
    <time class="text-uppercase fw-light mb-1 d-block w-fit"><%= post.date %></time>
    <h2 class="card-post-title m-0 lh-base"><%= link_to post.title, post_path(post) %></h2>
  </div>
</div>

app/views/posts/search.html.erb
<% custom_page_title('Search page') %>
<div class="container-lg py-4">
  <span>Showing <%= @posts.count %> results for</span>
  <h1><%= @query %></h1>
  <hr>
  <div class="row">
    <% if @posts.count > 0 %>
      <% @posts.each do |post| %>
        <%= render 'posts/partials/horizontal_card', post: post %>
      <% end %>
    <% else %>
      <h2 class="text-center">No results found...</h2>
    <% end %>
  </div>
</div>

app/views/posts/show.html.erb
<% custom_page_title(@post.title) %>
<% content_for(:meta_description) { excerpt((@post.content)) } %>
<% content_for(:meta_image) { cl_image_path @post.thumbnail.key, width: 1200, height: 630, crop: :fill } %>
<div class="post-header row">
  <div class="col-12 col-md-6 order-md-2 d-flex justify-content-center align-items-center text-center px-md-5">
    <div class="post-title">
      <h1><%= @post.title %></h1>
      <div class="my-3">
        <span class="text-uppercase fw-bold">by <%= link_to @post.user.full_name, author_path(@post.user) %></span>
      </div>
      <time class="text-uppercase fw-light"><%= @post.date %></time>
      <% if policy(@post).author? %>
        <div class="m-0 mt-3">
          <span class="text-uppercase fw-light">
            <%= link_to edit_post_path(@post) do %>
              <i class="fas fa-pencil-alt"></i>
            <% end %>
            <div class="d-inline post-separator"></div>
            <%= link_to post_path(@post), method: :delete, data: { confirm: "¿Estás seguro de eliminar #{@post.title}?" } do %>
              <i class="fas fa-trash-alt"></i>
            <% end %>
          </span>
        </div>
      <% end %>
    </div>
  </div>
  <div class="col-12 col-md-6 order-md-1 d-flex align-items-center p-0">
    <picture>
      <source srcset="<%= cl_image_path @post.thumbnail.key, width: 718, height: 718, crop: :fill, quality: 100 %> 1x, <%= cl_image_path @post.thumbnail.key, width: 1436, height: 1436, crop: :fill, quality: 100 %> 2x">
      <%= cl_image_tag @post.thumbnail.key, width: 718, height: 718, crop: :fill, quality: 100, alt: @post.title %>
    </picture>
  </div>
</div>
<div class="container-lg">
  <div class="post-content">
    <%= markdown(@post.content) %>
  </div>
  <% if @post.previous || @post.next %>
    <div class="post-nav row">
      <% if @post.previous %>
        <div class="col-6 post-nav-previous">
          <%= link_to post_path(@post.previous) do %>
            <span><i class="fas fa-long-arrow-alt-left"></i> Previous post</span>
            <%= @post.previous.title %>
          <% end %>
        </div>
      <% end %>
      <% if @post.next %>
        <div class="col-6 post-nav-next">
          <%= link_to post_path(@post.next) do %>
            <span>Next post <i class="fas fa-long-arrow-alt-right"></i></span>
            <%= @post.next.title %>
          <% end %>
        </div>
      <% end %>
    </div>
  <% end %>
</div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<footer id="footer" class="bg-black text-white py-4">
  <div class="container-lg">
    <h2>Markdown Blog</h2>
    <hr>
    <span>© 2022 Copyright</span>
  </div>
</footer>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-expand-md navbar-light navbar-markdown-blog">
  <div class="container-lg">
    <%= link_to root_path, class: "navbar-brand" do %>
      <h2>Markdown Blog</h2>
    <% end %>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto">
        <% if user_signed_in? %>
          <li class="nav-item dropdown">
            <%= link_to current_user.full_name, "#", class: "nav-link dropdown-toggle", id: "navbarDropdown", data: { bs_toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
            <ul class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
              <% if current_user.role == "editor" %>
                <%= link_to "New post", new_post_path, class: "dropdown-item" %>
                <%= link_to "My profile", author_path(current_user), class: "dropdown-item" %>
              <% end %>
              <%= link_to "Edit profile", edit_user_registration_path, class: "dropdown-item" %>
              <li><hr class="dropdown-divider"></li>
              <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
            </ul>
          </li>
        <% else %>
          <li class="nav-item">
            <%= link_to "Login", new_user_session_path, class: "nav-link" %>
          </li>
        <% end %>
        <%= render 'shared/search_navbar'%>
      </ul>
    </div>
  </div>
</nav>

app/views/shared/_pagy.html.erb
<%#
  This template is i18n-ready: if you don't use i18n, then you can replace the pagy_t
  calls with the actual strings ("&lsaquo; Prev", "Next &rsaquo;", "&hellip;").
  The link variable is set to a proc that returns the link tag.
  Usage: link.call( page_number [, text [, extra_attributes_string ]])
%>
<% _link = pagy_link_proc(pagy) %>
<nav id="pagy-author-posts" aria-label="pager">
  <ul class="w-100 justify-content-between d-flex p-0 list-unstyled">
    <%# Show only one button on page one %>
    <% if pagy.next && !pagy.prev %>
      <li class="pagy-author-button pagy-author-more mx-auto btn btn-primary"><%== _link.call(pagy.next, "Read more stories") %></li>
    <% end %>
    <% if pagy.prev %>
      <li class="pagy-author-button pagy-author-prev btn btn-primary"><%== _link.call(pagy.prev, "Previous") %></li>
    <% end %>
    <% if pagy.next && pagy.prev %>
      <li class="pagy-author-button pagy-author-next btn btn-primary"><%== _link.call(pagy.next, "Next") %></li>
    <% end %>
  </ul>
</nav>

app/views/shared/_search_navbar.html.erb
<%= simple_form_for :query, url: search_path, method: :get, html: { class: 'd-flex nav-search' } do |f| %>
  <%= f.input :title, placeholder: 'Find a post', label: false, wrapper: false, input_html: { value: params[:query] ? params[:query][:title] : '', class: 'ms-md-2' } %>
  <%= f.button :button, name: nil, class: 'btn-search' do %>
    <i class="fas fa-search"></i>
  <% end %>
<% end %>